### ISSUE TITLE
启动报错，这是什么原因呢？

### ISSUE THREAD

**Issue by seasonl2014** [kailong321200875/vue-element-plus-admin#29]
F:\学灯网录制的视频教程\前端脚手架20220407\vue-element-plus-admin-master\node_modules\.pnpm\registry.npmmirror.com+vite-plugin-html@3.2.0_vite@2.8.6\node_modules\vite-plugin-html\dist\index.cjs:125
      const proxy = viteConfig.server?.proxy ?? {};
                                      ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (F:\学灯网录制的视频教程\前端脚手架20220407\vue-element-plus-admin-master\vite.config.ts:46:31)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.require.extensions.<computed> [as .ts] (F:\学灯网录制的视频教程\前端脚手架20220407\vue-element-plus-admin-master\node_modules\.pnpm\registry.npmmirror.com+vite@2.8.6_less@4.1.2\node_modules\vite\dist\node\chunks\dep-9c153816.js:71416:20)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at loadConfigFromBundledFile (F:\学灯网录制的视频教程\前端脚手架20220407\vue-element-plus-admin-master\node_modules\.pnpm\registry.npmmirror.com+vite@2.8.6_less@4.1.2\node_modules\vite\dist\node\chunks\dep-9c153816.js:71424:17)
    at loadConfigFromFile (F:\学灯网录制的视频教程\前端脚手架20220407\vue-element-plus-admin-master\node_modules\.pnpm\registry.npmmirror.com+vite@2.8.6_less@4.1.2\node_modules\vite\dist\node\chunks\dep-9c153816.js:71343:32)
Waiting for the debugger to disconnect...
 ELIFECYCLE  Command failed with exit code 1.

**Comment by kailong321200875** [comment]
@seasonl2014 请提供下版本

**Comment by seasonl2014** [comment]
提供什么的版本？

**Comment by kailong321200875** [comment]
vue-element-plus-admin 的版本，我这边复现是没问题的。你是否是最新版本？

**Comment by seasonl2014** [comment]
> vue-element-plus-admin 的版本，我这边复现是没问题的。你是否是最新版本？

是的，是最新版本，今天刚刚下载下来的，导入vs code然后运行就报错了

**Comment by kailong321200875** [comment]
我这边把包删除在重新试试看

**Comment by kailong321200875** [comment]
请确保使用的是 pnpm 包管理器安装，我这边还是无法复现你的问题。
