### ISSUE TITLE
v2.4.0 启动报错

### ISSUE THREAD

**Issue by geekidentity** [kailong321200875/vue-element-plus-admin#361]
![image](https://github.com/kailong321200875/vue-element-plus-admin/assets/23332528/8d6e4ff8-2df6-41a0-83a7-6e08d9018775)

```shell
➜ pnpm -v
8.9.2

➜ node -v
v21.1.0
```

**Comment by geekidentity** [comment]
```
> vite --mode base

                                                                                                                                                                 5:30:46 PM
  VITE v4.4.11  ready in 1972 ms

  ➜  Local:   http://localhost:4000/                                                                                                                             5:30:46 PM
  ➜  Network: http://10.253.0.171:4000/                                                                                                                          5:30:46 PM
  ➜  press h to show help                                                                                                                                        5:30:46 PM

 ERROR  5:30:52 PM [vite] Internal server error:                                                                                                                 5:30:52 PM
/Users/houfachao/workspaces/vue-element-plus-admin/src/views/Login/Login.vue
  74:13  error  The element inside <transition> is expected to have a v-if or v-show directive  vue/require-toggle-inside-transition

✖ 1 problem (1 error, 0 warnings)

  Plugin: vite-plugin-eslint
  File: /Users/houfachao/workspaces/vue-element-plus-admin/src/views/Login/Login.vue
      at formatError (file:///Users/houfachao/workspaces/vue-element-plus-admin/node_modules/.pnpm/registry.npmmirror.com+vite@4.4.11_@types+node@20.8.8_less@4.2.0_terser@5.22.0/node_modules/vite/dist/node/chunks/dep-2b82a1ce.js:44055:46)
      at TransformContext.error (file:///Users/houfachao/workspaces/vue-element-plus-admin/node_modules/.pnpm/registry.npmmirror.com+vite@4.4.11_@types+node@20.8.8_less@4.2.0_terser@5.22.0/node_modules/vite/dist/node/chunks/dep-2b82a1ce.js:44051:19)
      at TransformContext.transform (/Users/houfachao/workspaces/vue-element-plus-admin/node_modules/.pnpm/registry.npmmirror.com+vite-plugin-eslint@1.8.1_eslint@8.52.0_vite@4.4.11/node_modules/vite-plugin-eslint/dist/index.js:1:2469)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Object.transform (file:///Users/houfachao/workspaces/vue-element-plus-admin/node_modules/.pnpm/registry.npmmirror.com+vite@4.4.11_@types+node@20.8.8_less@4.2.0_terser@5.22.0/node_modules/vite/dist/node/chunks/dep-2b82a1ce.js:44345:30)
      at async loadAndTransform (file:///Users/houfachao/workspaces/vue-element-plus-admin/node_modules/.pnpm/registry.npmmirror.com+vite@4.4.11_@types+node@20.8.8_less@4.2.0_terser@5.22.0/node_modules/vite/dist/node/chunks/dep-2b82a1ce.js:55015:29)
      at async viteTransformMiddleware (file:///Users/houfachao/workspaces/vue-element-plus-admin/node_modules/.pnpm/registry.npmmirror.com+vite@4.4.11_@types+node@20.8.8_less@4.2.0_terser@5.22.0/node_modules/vite/dist/node/chunks/dep-2b82a1ce.js:64417:32)


 ERROR  5:30:57 PM [vite] Internal server error:                                                                                                                 5:30:57 PM
/Users/houfachao/workspaces/vue-element-plus-admin/src/views/Login/Login.vue
  74:13  error  The element inside <transition> is expected to have a v-if or v-show directive  vue/require-toggle-inside-transition

✖ 1 problem (1 error, 0 warnings)

  Plugin: vite-plugin-eslint
  File: /Users/houfachao/workspaces/vue-element-plus-admin/src/views/Login/Login.vue
      at formatError (file:///Users/houfachao/workspaces/vue-element-plus-admin/node_modules/.pnpm/registry.npmmirror.com+vite@4.4.11_@types+node@20.8.8_less@4.2.0_terser@5.22.0/node_modules/vite/dist/node/chunks/dep-2b82a1ce.js:44055:46)
      at TransformContext.error (file:///Users/houfachao/workspaces/vue-element-plus-admin/node_modules/.pnpm/registry.npmmirror.com+vite@4.4.11_@types+node@20.8.8_less@4.2.0_terser@5.22.0/node_modules/vite/dist/node/chunks/dep-2b82a1ce.js:44051:19)
      at TransformContext.transform (/Users/houfachao/workspaces/vue-element-plus-admin/node_modules/.pnpm/registry.npmmirror.com+vite-plugin-eslint@1.8.1_eslint@8.52.0_vite@4.4.11/node_modules/vite-plugin-eslint/dist/index.js:1:2469)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Object.transform (file:///Users/houfachao/workspaces/vue-element-plus-admin/node_modules/.pnpm/registry.npmmirror.com+vite@4.4.11_@types+node@20.8.8_less@4.2.0_terser@5.22.0/node_modules/vite/dist/node/chunks/dep-2b82a1ce.js:44345:30)
      at async loadAndTransform (file:///Users/houfachao/workspaces/vue-element-plus-admin/node_modules/.pnpm/registry.npmmirror.com+vite@4.4.11_@types+node@20.8.8_less@4.2.0_terser@5.22.0/node_modules/vite/dist/node/chunks/dep-2b82a1ce.js:55015:29)
      at async viteTransformMiddleware (file:///Users/houfachao/workspaces/vue-element-plus-admin/node_modules/.pnpm/registry.npmmirror.com+vite@4.4.11_@types+node@20.8.8_less@4.2.0_terser@5.22.0/node_modules/vite/dist/node/chunks/dep-2b82a1ce.js:64417:32) (x2)
```

**Comment by kailong321200875** [comment]
node 换成16版本的试试看 @geekidentity

**Comment by notlaughingzzm** [comment]
同报错，node版本16.14.2

**Comment by chixianliangGithub** [comment]
我也有这个错误 
![Uploading image.png…]()

**Comment by chenyRain** [comment]
这是eslint-plugin-vue 引起的   transition中的div中需要加if或者show
[https://eslint.vuejs.org/rules/require-toggle-inside-transition.html](url)
```<template>
  <!-- ✓ GOOD -->
  <transition><div v-if="show" /></transition>
  <transition><div v-show="show" /></transition>

  <!-- ✗ BAD -->
  <transition><div /></transition>
</template>```

**Comment by Buster-00** [comment]
same
