### ISSUE TITLE
启动报错缺少包 Cannot find module @iconify-json/en

### ISSUE THREAD

**Issue by hackedbyxx** [kailong321200875/vue-element-plus-admin#420]
是不兼容NODEJS20吗，版本是v20.10.0

[17:19:20]  ERROR  17:19:20 [vite] Internal server error: Error: Cannot find module @iconify-json/en imported from file:///D:/DP/Trip/vue-element-plus-admin, file:///D:/DP/Trip/, file:///D:/DP/Trip/vue-element-plus-admin/_index.js, file:///D:/DP/Trip/node_modules
      at resolvePath (file:///D:/DP/Trip/vue-element-plus-admin/node_modules/.pnpm/mlly@1.5.0/node_modules/mlly/dist/index.mjs:2121:10)
      at task (file:///D:/DP/Trip/vue-element-plus-admin/node_modules/.pnpm/@iconify+utils@2.1.21/node_modules/@iconify/utils/lib/loader/fs.mjs:44:31)
      at async loadNodeIcon (file:///D:/DP/Trip/vue-element-plus-admin/node_modules/.pnpm/@iconify+utils@2.1.21/node_modules/@iconify/utils/lib/loader/node-loader.mjs:31:19)
      at async D:\DP\Trip\vue-element-plus-admin\node_modules\.pnpm\@unocss+preset-icons@0.58.4\node_modules\@unocss\preset-icons\dist\shared\preset-icons.5PH3fREn.cjs:811:22
      at async rules.layer.layer (D:\DP\Trip\vue-element-plus-admin\node_modules\.pnpm\@unocss+preset-icons@0.58.4\node_modules\@unocss\preset-icons\dist\shared\preset-icons.5PH3fREn.cjs:767:21)
      at async UnoGenerator.parseUtil (D:\DP\Trip\vue-element-plus-admin\node_modules\.pnpm\@unocss+core@0.58.4\node_modules\@unocss\core\dist\index.cjs:950:22)
      at async UnoGenerator.parseToken (D:\DP\Trip\vue-element-plus-admin\node_modules\.pnpm\@unocss+core@0.58.4\node_modules\@unocss\core\dist\index.cjs:684:120)
      at async D:\DP\Trip\vue-element-plus-admin\node_modules\.pnpm\@unocss+core@0.58.4\node_modules\@unocss\core\dist\index.cjs:719:23
      at async Promise.all (index 4)
      at async UnoGenerator.generate (D:\DP\Trip\vue-element-plus-admin\node_modules\.pnpm\@unocss+core@0.58.4\node_modules\@unocss\core\dist\index.cjs:740:5)
      at async generateCSS (D:\DP\Trip\vue-element-plus-admin\node_modules\.pnpm\@unocss+vite@0.58.4_rollup@4.9.6_vite@5.0.11\node_modules\@unocss\vite\dist\index.cjs:628:16)
      at async Context.load (D:\DP\Trip\vue-element-plus-admin\node_modules\.pnpm\@unocss+vite@0.58.4_rollup@4.9.6_vite@5.0.11\node_modules\@unocss\vite\dist\index.cjs:745:31)
      at async Object.load (file:///D:/DP/Trip/vue-element-plus-admin/node_modules/.pnpm/vite@5.0.11_@types+node@20.11.16_less@4.2.0_terser@5.27.0/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:64031:32) 
      at async loadAndTransform (file:///D:/DP/Trip/vue-element-plus-admin/node_modules/.pnpm/vite@5.0.11_@types+node@20.11.16_less@4.2.0_terser@5.27.0/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:49665:24)
      at async viteTransformMiddleware (file:///D:/DP/Trip/vue-element-plus-admin/node_modules/.pnpm/vite@5.0.11_@types+node@20.11.16_less@4.2.0_terser@5.27.0/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:59342:32) (x2)

**Comment by robertzml** [comment]
遇到同样问题

**Comment by hackedbyxx** [comment]
安装NVM降级到18就好了
`nvm install 18.19.0`
`nvm use 18.19.0`
`pnpm install node@18.19.0`
