### ISSUE TITLE
上传组件在build-pro的页面里在选择上传文件后会报错TypeError: t.upload.addEventListener is not a function

### ISSUE THREAD

**Issue by bursonyang** [kailong321200875/vue-element-plus-admin#431]
element-plus-Ix-kQ1m3.js:48 Uncaught (in promise) TypeError: t.upload.addEventListener is not a function
    at fR (element-plus-Ix-kQ1m3.js:48:182695)
    at element-plus-Ix-kQ1m3.js:48:190299
    at Generator.next (<anonymous>)
    at l (element-plus-Ix-kQ1m3.js:1:681)

**Comment by wshaobo** [comment]
楼上解决了吗？

**Comment by ChenPan0506** [comment]
ElUpload 组件如果使用的action绑定上传接口URL，把本地viteMockServe插件注释后打包即可解决，原因是mock组件和Elupload冲突

**Comment by ChenPan0506** [comment]
@b7wch
